PROGRESS_STEPS = {
  'AUDIO_DATA_OBTAINING_FINISHED': 'AUDIO_DATA_OBTAINING_FINISHED',
  'BPM_AND_BEAT_TIMES_RECOGNITION_FINISHED': 'BPM_AND_BEAT_TIMES_RECOGNITION_FINISHED',
  'CHORDS_RECOGNITION_FINISHED': 'CHORDS_RECOGNITION_FINISHED', 
  'BEATS_MAPPING_FINISHED': 'BEATS_MAPPING_FINISHED',
  'CHORDS_PER_BEATS_MAPPING_FINISHED': 'CHORDS_PER_BEATS_MAPPING_FINISHED',
}

RESPONSE_EVENTS = {
  'PROGRESS': 'PROGRESS',
  'ERROR': 'ERROR',
  'SUCCESS': 'SUCCESS'
}